//
// Created by nick on 06/06/2023.
//

#ifndef ENIGMA_REFLECTOR_H
#define ENIGMA_REFLECTOR_H

#define A "EJMZALYXVBWFCRQUONTSPIKHGD"
#define B "YRUHQSLDPXNGOKMIEBFZCWVJAT"
#define C "FVPJIAOYEDRZXWGCTKUQSBNMHL"

#endif //ENIGMA_REFLECTOR_H
